### ISSUE TITLE
telegram.error.NetworkError: Bad Gateway

### ISSUE THREAD

**Issue by DmytroLitvinov** [lorcalhost/BTB-manager-telegram#142]
Here is a traceback of error:
```
2021-10-22 01:10:23,711 - telegram.ext.updater - ERROR - Error while getting Updates: Bad Gateway
2021-10-22 01:10:23,712 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/manager/binance-trade-bot-pilot-usdt/binance-trade-bot/venv/lib/python3.8/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/manager/binance-trade-bot-pilot-usdt/binance-trade-bot/venv/lib/python3.8/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/manager/binance-trade-bot-pilot-usdt/binance-trade-bot/venv/lib/python3.8/site-packages/telegram/ext/extbot.py", line 222, in get_updates
    updates = super().get_updates(
  File "/home/manager/binance-trade-bot-pilot-usdt/binance-trade-bot/venv/lib/python3.8/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/manager/binance-trade-bot-pilot-usdt/binance-trade-bot/venv/lib/python3.8/site-packages/telegram/bot.py", line 2861, in get_updates
    self._post(
  File "/home/manager/binance-trade-bot-pilot-usdt/binance-trade-bot/venv/lib/python3.8/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/manager/binance-trade-bot-pilot-usdt/binance-trade-bot/venv/lib/python3.8/site-packages/telegram/utils/request.py", line 356, in post
    result = self._request_wrapper(
  File "/home/manager/binance-trade-bot-pilot-usdt/binance-trade-bot/venv/lib/python3.8/site-packages/telegram/utils/request.py", line 290, in _request_wrapper
    raise NetworkError('Bad Gateway')
telegram.error.NetworkError: Bad Gateway
2021-10-22 01:10:25,022 - telegram.ext.updater - ERROR - Error while getting Updates: Bad Gateway
2021-10-22 01:10:25,023 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/manager/binance-trade-bot-pilot-usdt/binance-trade-bot/venv/lib/python3.8/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/manager/binance-trade-bot-pilot-usdt/binance-trade-bot/venv/lib/python3.8/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/manager/binance-trade-bot-pilot-usdt/binance-trade-bot/venv/lib/python3.8/site-packages/telegram/ext/extbot.py", line 222, in get_updates
    updates = super().get_updates(
  File "/home/manager/binance-trade-bot-pilot-usdt/binance-trade-bot/venv/lib/python3.8/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/manager/binance-trade-bot-pilot-usdt/binance-trade-bot/venv/lib/python3.8/site-packages/telegram/bot.py", line 2861, in get_updates
    self._post(
  File "/home/manager/binance-trade-bot-pilot-usdt/binance-trade-bot/venv/lib/python3.8/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/manager/binance-trade-bot-pilot-usdt/binance-trade-bot/venv/lib/python3.8/site-packages/telegram/utils/request.py", line 356, in post
    result = self._request_wrapper(
  File "/home/manager/binance-trade-bot-pilot-usdt/binance-trade-bot/venv/lib/python3.8/site-packages/telegram/utils/request.py", line 290, in _request_wrapper
    raise NetworkError('Bad Gateway')
telegram.error.NetworkError: Bad Gateway
```

**Comment by DmytroLitvinov** [comment]
Hi @titulebolide ,
Unfortunately, I can't.
Right now seems there is no issue.
