### ISSUE TITLE
i18n translation other than en break bot commands

### ISSUE THREAD

**Issue by titulebolide** [lorcalhost/BTB-manager-telegram#152]
```python
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/titus/BTB-manager-telegram/btb_manager_telegram/__main__.py", line 149, in <module>
    main()
  File "/home/ubuntu/titus/BTB-manager-telegram/btb_manager_telegram/__main__.py", line 97, in main
    from btb_manager_telegram import handlers
  File "/home/ubuntu/titus/BTB-manager-telegram/btb_manager_telegram/handlers.py", line 665, in <module>
    FALLBACK_HANDLER = CommandHandler(i18n.t("keyboard.fb_cancel"), cancel)
  File "/home/ubuntu/titus/BTB-manager-telegram/venv/lib/python3.8/site-packages/telegram/ext/commandhandler.py", line 163, in __init__
    raise ValueError('Command is not a valid bot command')
ValueError: Command is not a valid bot command
```

**Comment by titulebolide** [comment]
Invoking  @Lisiadito on this one :)

**Comment by Lisiadito** [comment]
What was the command you used to run the bot? And right now only english translations are present.

**Comment by titulebolide** [comment]
Actually #133 added russian translation
I ran `python -m btb_manager_telegram -l ru`

**Comment by Lisiadito** [comment]
Ah I remember. Someone wrote me who wanted to implement a Vietnamese translation and as far as I remember it was a problem with unicode characters in the translation file. I see if I can reach out to that person and find out how they fixed it.

**Comment by titulebolide** [comment]
But russian characters are unicode? (btw we are already using emojis so i'm not sure that it is the problem...)

**Comment by Lisiadito** [comment]
Maybe I'm wrong thats just what I remember. The person wrote me a few weeks ago on discord. I wrote that person to find out what was the problem. 
But actually on the main branch I get another error even when I let it run with the default language.

```
python3 -m btb_manager_telegram
2021-11-19 15:44:18,369 - btb_manager_telegram_logger - INFO - Retrieving Telegram token and chat_id from apprise.yml file.
2021-11-19 15:44:18,373 - btb_manager_telegram_logger - INFO - Successfully retrieved Telegram configuration. The bot will only respond to user in the chat with chat_id 165252546
2021-11-19 15:44:19,374 - btb_manager_telegram_logger - INFO - Checking for updates.
2021-11-19 15:44:35,934 - btb_manager_telegram_logger - INFO - Binance Trade Bot update found.
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/code/binanceWebsocketFork/BTB-manager-telegram/btb_manager_telegram/__main__.py", line 148, in <module>
    pre_run_main()
  File "/home/pi/code/binanceWebsocketFork/BTB-manager-telegram/btb_manager_telegram/__main__.py", line 91, in pre_run_main
    scheduler.run(blocking=False)
  File "/usr/lib/python3.7/sched.py", line 151, in run
    action(*argument, **kwargs)
  File "/home/pi/code/binanceWebsocketFork/BTB-manager-telegram/btb_manager_telegram/utils.py", line 197, in update_checker
    bot.close()
  File "/home/pi/.local/lib/python3.7/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/telegram/bot.py", line 5234, in close
    return self._post('close', timeout=timeout)  # type: ignore[return-value]
  File "/home/pi/.local/lib/python3.7/site-packages/telegram/bot.py", line 296, in _post
    f'{self.base_url}/{endpoint}', data=data, timeout=effective_timeout
  File "/home/pi/.local/lib/python3.7/site-packages/telegram/utils/request.py", line 361, in post
    **urlopen_kwargs,
  File "/home/pi/.local/lib/python3.7/site-packages/telegram/utils/request.py", line 272, in _request_wrapper
    message = str(self._parse(resp.data))
  File "/home/pi/.local/lib/python3.7/site-packages/telegram/utils/request.py", line 230, in _parse
    raise RetryAfter(retry_after)
telegram.error.RetryAfter: Flood control exceeded. Retry in 515.0 seconds
```

Thats super strange because I was using my branch for weeeks without problems. So I guess it's maybe a combination of changes on main and the russian branch and my changes. We maybe should've merged the main into the feature branches before we merge everything into main.

**Comment by titulebolide** [comment]
The flood control error is when you spammed too much tg with the bot apparently

**Comment by Lisiadito** [comment]
so you dont get this error when you start it in english mode?

**Comment by titulebolide** [comment]
which one, yours or mine? yours, even in english mode. mine, only with russian

**Comment by Lisiadito** [comment]
I was asking for the flood controll error. Yeah I get that in english mode. Thats due to the bug I reported #118 
And yeah your error I only get with the russian language selection. I would recommend to rollback the merge of the russian translation until we find the reason or?

**Comment by titulebolide** [comment]
i am working on it, I'm thinking about leaving the russian translation here as we can default to en translation

**Comment by titulebolide** [comment]
This is not good : https://github.com/python-telegram-bot/python-telegram-bot/blob/2f6c4075c866e4e03dccb2b1f41c1fa550e00d93/telegram/ext/commandhandler.py#L162

**Comment by Lisiadito** [comment]
true we're defaulting to english anyway so it's ok.

And about the regex. What is exactly the problem?

**Comment by titulebolide** [comment]
It only accepts commands with characters between a and z of less than 32 characters.
Actually it set up two things : commands and messages, and messages is what it used with emojis and stuff, which accepts all unicode, but command (for basic cancel and start) have to be lowercase and between a and z

**Comment by titulebolide** [comment]
![Screenshot_20211119_161031_org.telegram.messenger.jpg](https://user-images.githubusercontent.com/44905741/142645396-1bb253ae-7f7b-4a74-8b5c-540081cfaf93.jpg)
Did the trick

**Comment by titulebolide** [comment]
Merged :) thanks for the help
