### ISSUE TITLE
Problem with starting the bot

### ISSUE THREAD

**Issue by Jaszczur11** [lorcalhost/BTB-manager-telegram#205]
Has a problem with starting the bot. I get this message:

E:\btbm>python3 -m btb_manager_telegram
C:\Users\Jaszczur\AppData\Local\Programs\Python\Python39\python3.exe: No module named btb_manager_telegram

**Comment by titulebolide** [comment]
it says what it says :)
you are highly likely not in the good folder.
if you ran the `git clone` command in th folder `E:\btbm`, then you have to run `dir BTB-manager-telegram` because the module `btb_manager_telegram` is located in this new folder.

**Comment by Jaszczur11** [comment]
Now I have :

E:\btbm\BTB-manager-telegram>python3 -m btb_manager_telegram
Traceback (most recent call last):
  File "C:\Users\Jaszczur\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Jaszczur\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\btbm\BTB-manager-telegram\btb_manager_telegram\__main__.py", line 239, in <module>
    pre_run_main()
  File "E:\btbm\BTB-manager-telegram\btb_manager_telegram\__main__.py", line 123, in pre_run_main
    setup_i18n(settings.LANG)
  File "E:\btbm\BTB-manager-telegram\btb_manager_telegram\utils.py", line 19, in setup_i18n
    i18n.set("locale", lang)
AttributeError: module 'i18n' has no attribute 'set'

**Comment by titulebolide** [comment]
Please read carefully the readme you are missing steps

**Comment by Jaszczur11** [comment]
I do not know. I still have the same.

**Comment by titulebolide** [comment]
Try to do the following :
```
pip3 uninstall i18n
pip install i18n
```
Sometimes the install of i18n messes up for no apparent reason

**Comment by Jaszczur11** [comment]
No change.

E:\btbm\BTB-manager-telegram>pip3 uninstall i18n
WARNING: Skipping i18n as it is not installed.

E:\btbm\BTB-manager-telegram>pip install i18n
Collecting i18n
  Downloading i18n-0.2.tar.gz (6.5 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: py in c:\users\jaszczur\appdata\local\programs\python\python39\lib\site-packages (from i18n) (1.10.0)
Requirement already satisfied: babel in c:\users\jaszczur\appdata\local\programs\python\python39\lib\site-packages (from i18n) (2.9.1)
Requirement already satisfied: pytz>=2015.7 in c:\users\jaszczur\appdata\local\programs\python\python39\lib\site-packages (from babel->i18n) (2021.3)
Using legacy 'setup.py install' for i18n, since package 'wheel' is not installed.
Installing collected packages: i18n
    Running setup.py install for i18n ... done
Successfully installed i18n-0.2

E:\btbm\BTB-manager-telegram>python3 -m btb_manager_telegram
Traceback (most recent call last):
  File "C:\Users\Jaszczur\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Jaszczur\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\btbm\BTB-manager-telegram\btb_manager_telegram\__main__.py", line 239, in <module>
    pre_run_main()
  File "E:\btbm\BTB-manager-telegram\btb_manager_telegram\__main__.py", line 123, in pre_run_main
    setup_i18n(settings.LANG)
  File "E:\btbm\BTB-manager-telegram\btb_manager_telegram\utils.py", line 19, in setup_i18n
    i18n.set("locale", lang)
AttributeError: module 'i18n' has no attribute 'set'

**Comment by titulebolide** [comment]
My apologies. I did a mistake.
Please run
```
pip3 uninstall i18n
pip3 uninstall python-i18n
pip3 install python-i18n
```

**Comment by Jaszczur11** [comment]
Now I have other bugs. I uninstalled BTB-manager-telegram and reinstalled. Unfortunately, no changes.

E:\btbm\BTB-manager-telegram>python3 -m btb_manager_telegram
2021-12-21 21:55:34,650 - btb_manager_telegram_logger - INFO - Retreiving binance tokens
Traceback (most recent call last):
  File "C:\Users\Jaszczur\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Jaszczur\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\btbm\BTB-manager-telegram\btb_manager_telegram\__main__.py", line 239, in <module>
    pre_run_main()
  File "E:\btbm\BTB-manager-telegram\btb_manager_telegram\__main__.py", line 125, in pre_run_main
    retreive_btb_constants()
  File "E:\btbm\BTB-manager-telegram\btb_manager_telegram\utils.py", line 113, in retreive_btb_constants
    settings.BINANCE_API_KEY = btb_config.get("binance_user_config", "api_key")
  File "C:\Users\Jaszczur\AppData\Local\Programs\Python\Python39\lib\configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "C:\Users\Jaszczur\AppData\Local\Programs\Python\Python39\lib\configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'binance_user_config'

**Comment by titulebolide** [comment]
It seems the user.cfg file from the binance_trade_bot is missing its very first line : `[binance_user_config]`

**Comment by Jaszczur11** [comment]
This line is in the file.

[binance_user_config]
# All config params are explained in depth in the repo.

# API key and Secret key created on Binance
api_key=XXXXX
api_secret_key=XXXX

# Starting coin, leave empty when it's the bridge.
# It has to be in the supported_coin_list
current_coin=

#Bridge coin of your choice
bridge=BUSD

#com or us, depending on region
tld=com

#Defines how long the scout history is stored
hourToKeepScoutHistory=1

#Defines to use either scout_margin or scout_multiplier
use_margin=no

# It's recommended to use something between 3-7 as scout_multiplier
scout_multiplier=5

#It's recommended to use something between 0.3 and 1.2 as scout_margin
scout_margin=0.8

# Controls how many seconds bot should wait between analysis of current prices
scout_sleep_time=1

# Pre-configured strategies are default and multiple_coins
# strategy=default
strategy=multiple_coins

# Controls how many minutes to wait before cancelling a limit order (buy/sell) and returning to "scout" mode.
# 0 means that the order will never be cancelled prematurely.
buy_timeout=20
sell_timeout=20

**Comment by Jaszczur11** [comment]
Hello.
And no ideas what can be done?

**Comment by MasaiasuOse** [comment]
Do you have it like that:
```
PARENT_DIR
  ├── BTB-manager-telegram
  └── binance-trade-bot
```

**Comment by Jaszczur11** [comment]
![image](https://user-images.githubusercontent.com/50039853/147140359-fafd0f46-601a-46de-89f9-c0a4b2ac01fd.png)

**Comment by titulebolide** [comment]
It should be binance-trade-bot not binance_trade_bot

**Comment by titulebolide** [comment]
Update: the telegram bot is currently **in** the folder of the trading bot.
But the telegram bot and the trading bot must be in the same folder.

**Comment by Jaszczur11** [comment]
Super!!! It works. :)

**Comment by titulebolide** [comment]
Glad to see that! Closing this.
