### ISSUE TITLE
Error with configuration commands win WIN 10

### ISSUE THREAD

**Issue by javiramos** [lorcalhost/BTB-manager-telegram#54]
Hey mate! 
Thanks for your AWESOME work with this bot! Is amazing!
I run the bot well, all is working except the all commands relating to files or processes.
I attach you the error code, im not just asking, i tried everything, trying to debug in stackoverflow....
I know is a permission problem, i tried running as administrator binance_bot and telegram_bot with the same errors.

I hope you can help me friend

Thanks another time

MUCHAS GRACIAS AMIGO ITALIANO!

```
2021-04-15 20:38:28,571 - __main__ - INFO - Menu selector. (⚙ Edit user.cfg)
2021-04-15 20:38:28,571 - __main__ - INFO - Edit user configuration button pressed.
2021-04-15 20:38:28,579 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\tiwes\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\psutil\_pswindows.py", line 780, in cmdline
    ret = cext.proc_cmdline(self.pid, use_peb=True)
PermissionError: [WinError 5] Acceso denegado: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tiwes\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\tiwes\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\psutil\_pswindows.py", line 695, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\tiwes\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\psutil\_pswindows.py", line 783, in cmdline
    ret = cext.proc_cmdline(self.pid, use_peb=False)
PermissionError: [Errno 13] assume access denied (originated from NtQueryInformationProcess(ProcessBasicInformation) -> STATUS_NOT_FOUND)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tiwes\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\telegram\ext\dispatcher.py", line 442, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\tiwes\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\telegram\ext\conversationhandler.py", line 549, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "C:\Users\tiwes\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\telegram\ext\handler.py", line 160, in handle_update
    return self.callback(update, context)
  File "C:\Users\tiwes\desktop\CRIPTO APPS\BTB-manager-telegram\BTBManagerTelegram.py", line 242, in __menu
    re = self.__btn_edit_user_cfg()
  File "C:\Users\tiwes\desktop\CRIPTO APPS\BTB-manager-telegram\BTBManagerTelegram.py", line 728, in __btn_edit_user_cfg
    if not self.__find_process():
  File "C:\Users\tiwes\desktop\CRIPTO APPS\BTB-manager-telegram\BTBManagerTelegram.py", line 457, in __find_process
    p.cmdline()
  File "C:\Users\tiwes\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\psutil\__init__.py", line 677, in cmdline
    return self._proc.cmdline()
  File "C:\Users\tiwes\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=124, name='Registry')
```

**Comment by lorcalhost** [comment]
Hi! Thanks for your kind words.  
Although it is an experimental feature you can [try running the bot via docker](https://github.com/lorcalhost/BTB-manager-telegram/blob/main/docs/docker-setup.md).  

To do so run the command
```console
$ python3 docker_setup.py
```
to set up the environment and Docker image.

After the setup you can run the bot using the `--docker` flag:
```console
$ python3 -m btb_manager_telegram --docker
```

Let me know if this helps :)
