### ISSUE TITLE
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception. Traceback (most recent call last)

### ISSUE THREAD

**Issue by d4kr** [lorcalhost/BTB-manager-telegram#65]
Hi, I just install the Telegram Bot on my Debian 10 VPS with Python 3.9.4 but I get this error:

 ```console
2021-04-26 23:55:14,370 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/me/environments/binance39/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 442, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/me/environments/binance39/lib/python3.9/site-packages/telegram/ext/conversationhandler.py", line 549, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "/home/me/environments/binance39/lib/python3.9/site-packages/telegram/ext/handler.py", line 160, in handle_update
    return self.callback(update, context)
  File "/home/me/BTB-manager-telegram/btb_manager_telegram/handlers.py", line 251, in start
    update.message.reply_text(
  File "/home/me/environments/binance39/lib/python3.9/site-packages/telegram/message.py", line 689, in reply_text
    return self.bot.send_message(
  File "/home/me/environments/binance39/lib/python3.9/site-packages/telegram/bot.py", line 127, in decorator
    result = func(*args, **kwargs)
  File "/home/me/environments/binance39/lib/python3.9/site-packages/telegram/bot.py", line 475, in send_message
    return self._message(  # type: ignore[return-value]
  File "/home/me/environments/binance39/lib/python3.9/site-packages/telegram/bot.py", line 296, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/home/me/environments/binance39/lib/python3.9/site-packages/telegram/bot.py", line 259, in _post
    return self.request.post(
  File "/home/me/environments/binance39/lib/python3.9/site-packages/telegram/utils/request.py", line 349, in post
    result = self._request_wrapper(
  File "/home/me/environments/binance39/lib/python3.9/site-packages/telegram/utils/request.py", line 272, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse entities: can't find end of bold entity at byte offset 9
```

I have also tried with Python 3.7 (which is the default in Debian 10) without chance. What I do wrong?
Thanks for any advice.
Dav

**Comment by lorcalhost** [comment]
Hi @d4kr !  
Did you install all dependencies  listed in the `requirements.txt` file? Make sure those modules are updated to the specified version.  

This is the first time this problem has been reported but it seems like it has something to do with your `python-telegram-bot` dependency installation.  

Could you also specify when you get this error? Can you provide some steps to replicate the issue?
Grazie 😄

**Comment by d4kr** [comment]
Hi @ lorcalhost

What I did was to create a `venv` for python 3.7 and one for python 3.9 (installed from source). Install the dependencies from `requirements.txt` (I checked them all and they are there) and run the BOT.

binance-trade-bot and BTB-manager-telegram are at the same level of my home. In binance-trade-bot I have configured `apprise.yml` and in fact I receive the messages of the transactions made by the bot. However, if I try to start the bot with `/start` I get this error.

I can try to recreate the channel in Telegram and see if the error changes?
Grazie a te :-)

**Comment by DmytroLitvinov** [comment]
The problem with markdown which is tried to be sent.
> telegram.error.BadRequest: Can't parse entities: can't find end of bold entity at byte offset 9

More details: https://github.com/python-telegram-bot/python-telegram-bot/issues/131#issuecomment-167003086

Probably it is cut somewhere in the text.

**Comment by lorcalhost** [comment]
@d4kr Could you please provide your Telegram username? Does it contain any `-`s or other special characters?

**Comment by d4kr** [comment]
right, my display name started with an underscore. Thx
