### ISSUE TITLE
telegram.error.RetryAfter: Flood control exceeded

### ISSUE THREAD

**Issue by anhntsi** [lorcalhost/BTB-manager-telegram#66]
Hi I have install the bot on my raspberry pi with python 3.7.3 but I get this error:
```
2021-04-27 06:40:14,524 - btb_manager_telegram_logger - INFO - Retrieving Telegram token and chat_id from apprise.yml file.
2021-04-27 06:40:14,540 - btb_manager_telegram_logger - INFO - Successfully retrieved Telegram configuration. The bot will only respond to user in the chat with chat_id 1321341011
2021-04-27 06:40:15,542 - btb_manager_telegram_logger - INFO - Checking for updates.
2021-04-27 06:40:17,000 - btb_manager_telegram_logger - INFO - BTB Manager Telegram update found.
2021-04-27 06:40:21,123 - btb_manager_telegram_logger - INFO - Binance Trade Bot update found.
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/binance/BTB-manager-telegram/btb_manager_telegram/__main__.py", line 126, in <module>
    pre_run_main()
  File "/home/pi/binance/BTB-manager-telegram/btb_manager_telegram/__main__.py", line 70, in pre_run_main
    scheduler.run(blocking=False)
  File "/usr/lib/python3.7/sched.py", line 151, in run
    action(*argument, **kwargs)
  File "/home/pi/binance/BTB-manager-telegram/btb_manager_telegram/utils.py", line 174, in update_checker
    bot.close()
  File "/home/pi/.local/lib/python3.7/site-packages/telegram/bot.py", line 127, in decorator
    result = func(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/telegram/bot.py", line 4966, in close
    return self._post('close', timeout=timeout)  # type: ignore[return-value]
  File "/home/pi/.local/lib/python3.7/site-packages/telegram/bot.py", line 260, in _post
    f'{self.base_url}/{endpoint}', data=data, timeout=effective_timeout
  File "/home/pi/.local/lib/python3.7/site-packages/telegram/utils/request.py", line 354, in post
    **urlopen_kwargs,
  File "/home/pi/.local/lib/python3.7/site-packages/telegram/utils/request.py", line 265, in _request_wrapper
    message = str(self._parse(resp.data))
  File "/home/pi/.local/lib/python3.7/site-packages/telegram/utils/request.py", line 223, in _parse
    raise RetryAfter(retry_after)
telegram.error.RetryAfter: Flood control exceeded. Retry in 598.0 seconds
```

How do I fix it?

**Comment by lorcalhost** [comment]
I will look into this.  
For a quick fix you can manually update `binance-trade-bot` by running the `git pull` command inside the `binance-trade-bot` directory.

**Comment by Dgetsylver** [comment]
Unfortunately, it hasn't solved the problem for me.

**Comment by jvzl** [comment]
Looks like the flood control is exceeded when the trading bot creates a new database. Too many messages at once.

**Comment by titulebolide** [comment]
It did not fixed it, however I pushed something on fix/flood-control that might do the trick
