### ISSUE TITLE
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

### ISSUE THREAD

**Issue by SH-Stark** [lorcalhost/BTB-manager-telegram#69]
Hello, I had to restart the bot so I killed it and run it again, but now I'm having this error:

```
2021-04-27 16:35:52,906 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2021-04-27 16:35:52,906 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/telegram/ext/updater.py", line 516, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/telegram/ext/updater.py", line 467, in polling_action_cb
    updates = self.bot.get_updates(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/telegram/bot.py", line 127, in decorator
    result = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/telegram/bot.py", line 2761, in get_updates
    result = self._post(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/telegram/bot.py", line 259, in _post
    return self.request.post(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/telegram/utils/request.py", line 349, in post
    result = self._request_wrapper(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/telegram/utils/request.py", line 276, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
```

Do you have any idea how to kill the other instance ? Thanks

**Comment by lorcalhost** [comment]
Follow the steps in [this troubleshooting guide](https://github.com/lorcalhost/BTB-manager-telegram/blob/main/docs/troubleshooting.md#2-error-make-sure-that-only-one-bot-instance-is-running).

**Comment by SH-Stark** [comment]
Thanks!
