### ISSUE TITLE
File can't be found

### ISSUE THREAD

**Issue by Nesonica** [lorcalhost/BTB-manager-telegram#85]
Hi awesome guys and thanks for this awesome bot!

When trying to run the bot with:
python -m btb_manager_telegram -t xxxxx -c xxxxx

It will tell me (on Pycharm):
[WInError 2] The system could not find the file.

![unknown](https://user-images.githubusercontent.com/12950714/117597235-72187f80-b145-11eb-933c-de3afbdb0a00.png)

When running it with:
(venv) C:\Users\Nesin\PycharmProjects\binance-trade-bot>cd C:\Users\Nesin\PycharmProjects\BTB-manager-telegram

(venv) C:\Users\Nesin\PycharmProjects\BTB-manager-telegram>python -m btb_manager_telegram -p binance-trade-bot
2021-05-10 03:47:20,154 - btb_manager_telegram_logger - INFO - Retrieving Telegram token and chat_id from apprise.yml file.
2021-05-10 03:47:20,154 - btb_manager_telegram_logger - ERROR - Unable to find apprise.yml file at "binance-trade-bot\config/apprise.yml". Aborting.

![unknown-1](https://user-images.githubusercontent.com/12950714/117597359-b3a92a80-b145-11eb-8a11-02c668c7ba30.png)

What am I doing wrong?

**Comment by lorcalhost** [comment]
Try starting it as
```bash
python -m btb_manager_telegram -p "../binance-trade-bot"
```
or

```bash
python -m btb_manager_telegram
```

Also keep in mind using `venv` might mess with accessing files in the other trading bot's repository.

**Comment by pesado1** [comment]
same here too

**Comment by lorcalhost** [comment]
Can you try without using a `venv`?

**Comment by Nesonica** [comment]
Same story here :-)

![image](https://user-images.githubusercontent.com/12950714/117637573-351eae00-b182-11eb-9484-886dd45ee992.png)

**Comment by pesado1** [comment]
no go for me

**Comment by lorcalhost** [comment]
After debugging a bit with @Nesonica we figured out this may be related to pycharm.

Can you try to run the bot through another terminal?

**Comment by Nesonica** [comment]
> After debugging a bit with @Nesonica we figured out this may be related to pycharm.
> 
> Can you try to run the bot through another terminal? @pesado1

Hey man thanks for constantly working on it and helping out! So should I just remove the folder, make another clone and run with the settings we discussed yesterday?

**Comment by Nesonica** [comment]
**Unfortunately the error remains**

C:\Users\Nesin\PycharmProjects\BTB-manager-telegram\BTB-manager-telegram>python -m btb_manager_telegram
2021-05-11 10:04:15,251 - btb_manager_telegram_logger - INFO - Retrieving Telegram token and chat_id from apprise.yml file.
2021-05-11 10:04:15,251 - btb_manager_telegram_logger - ERROR - Unable to find apprise.yml file at "../binance-trade-bot/config/apprise.yml". Aborting.

C:\Users\Nesin\PycharmProjects\BTB-manager-telegram\BTB-manager-telegram>python -m btb_manager_telegram -t XXXXX -c XXXXX

2021-05-11 10:06:56,786 - btb_manager_telegram_logger - INFO - Checking for updates.
2021-05-11 10:06:56,790 - btb_manager_telegram_logger - ERROR - [WinError 2] Das System kann die angegebene Datei nicht finden
2021-05-11 10:06:56,795 - btb_manager_telegram_logger - ERROR - [WinError 2] Das System kann die angegebene Datei nicht finden
2021-05-11 10:06:57,886 - apscheduler.scheduler - INFO - Scheduler started

**Comment by lorcalhost** [comment]
You should run it inside `C:\Users\Nesin\PycharmProjects\BTB-manager-telegram` not `C:\Users\Nesin\PycharmProjects\BTB-manager-telegram\BTB-manager-telegram`

**Comment by Nesonica** [comment]
> You should run it inside `C:\Users\Nesin\PycharmProjects\BTB-manager-telegram` not `C:\Users\Nesin\PycharmProjects\BTB-manager-telegram\BTB-manager-telegram`

Same error in this folder. 👍

**Comment by lorcalhost** [comment]
I really am unable to pinpoint your issue, I spent some hours trying to figure it out but no luck so far.

If you really want to run the telegram bot you can still use it through WSL on windows or try the dockerized version although it's experimental.

**Comment by arby1108** [comment]
I fixed editing line 21 in utils.py

![imagen](https://user-images.githubusercontent.com/42874555/118054503-618a2400-b354-11eb-803a-940a7534dc85.png)

**Comment by pesado1** [comment]
PermissionError: [Errno 13] Permission denied: '../binance-trade-bot/../'

**Comment by pesado1** [comment]
oh wait

**Comment by Nesonica** [comment]
C:\Users\Nesin\PycharmProjects\BTB-manager-telegram>python -m btb_manager_telegram -t XXXXX -c XXXXX
2021-05-13 14:12:46,654 - btb_manager_telegram_logger - INFO - Checking for updates.
2021-05-13 14:12:46,657 - btb_manager_telegram_logger - ERROR - [WinError 2] Das System kann die angegebene Datei nicht finden
Traceback (most recent call last):
  File "C:\Users\Nesin\PycharmProjects\BTB-manager-telegram\btb_manager_telegram\utils.py", line 121, in is_tg_bot_update_available
    proc = subprocess.Popen(
  File "C:\Program Files\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
2021-05-13 14:12:46,672 - btb_manager_telegram_logger - ERROR - [WinError 2] Das System kann die angegebene Datei nicht finden
Traceback (most recent call last):
  File "C:\Users\Nesin\PycharmProjects\BTB-manager-telegram\btb_manager_telegram\utils.py", line 135, in is_btb_bot_update_available
    proc = subprocess.Popen(
  File "C:\Program Files\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
2021-05-13 14:12:47,774 - apscheduler.scheduler - INFO - Scheduler started

**Comment by arby1108** [comment]
I have same error, but anyway  the bot is working. 
that error mean the bot can't find updates only, but other functions are working properly

**Comment by Nesonica** [comment]
> I have same error, but anyway the bot is working.
> that error mean the bot can't find updates only, but other functions are working properly

Thanks for your update! So how can I test if it's working? I received no message from my bot yet.

**Comment by arby1108** [comment]
did you /start the bot?

**Comment by Nesonica** [comment]
> did you /start the bot?

Yes I did. I get a welcome message and that's all :D

**Comment by arby1108** [comment]
so click on Begin button

**Comment by Nesonica** [comment]
Where can I find that Begin Button? :)

**Comment by arby1108** [comment]
![imagen](https://user-images.githubusercontent.com/42874555/118128025-5ec91680-b3c8-11eb-833b-26c70f63747e.png)

**Comment by Nesonica** [comment]
Ahaaaaa! Thanks so much man!
